### ISSUE TITLE
Downgrades my requests

### ISSUE THREAD

**Issue by flying-sheep** [se7entyse7en/requests-throttler#10]
Please don’t pin versions

**Comment by bmarika** [comment]
Facing this issue as well. since requests is pinned to version 2.1.0.  Master is up-to-date. is it possible to do a release?

**Comment by flying-sheep** [comment]
Ah, this is fixed in #11, but not in a released version yet.

**Comment by se7entyse7en** [comment]
I'm really sorry guys for the delay, I know that this project was kind-of abandoned. I've just released a new version as you requested. Here it is: https://pypi.org/project/RequestsThrottler/.
